### PR TITLE
Normalizing namespace

### PR DESCRIPTION
**Pull request by fraga**
Getting rid of the _ :)

### CODE REVIEW

**Comment by celluj34** [comment]
IMO you should omit the test naming changes - this PR is big enough (and is a breaking change). Simpler is better.

**Comment by fraga** [comment]
Sure, I will change it and uodate the PR

**Comment by fraga** [comment]
@celluj34 there you go, needed to rebase I think that's fine

**Comment by ndsvw** [comment]
Thank you very much.
Was removing the dashes of the test method names intended?
My previous test method naming was probably not perfect, but there are naming strategies containing dashes (https://stackoverflow.com/questions/155436/unit-test-naming-best-practices) and Microsoft recommends a naming strategy with dashes, too: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices
I think, they are harder to read without the dash(es).

**Comment by fraga** [comment]
Sure @ndsvw I can certainly refactor it! Give me some moment and I will correct it for you.

**Comment by fraga** [comment]
@ndsvw as you can see first commit changes the namespace while the second just move files around folders, let me know your thoughts

**Comment by celluj34** [comment]
You created the new files but didn't delete the old ones...

**Comment by fraga** [comment]
Indeed so odd. On my branch local they are not here and even after --force it doesn't update it. Let me check

**Comment by fraga** [comment]
yeah so only after removing my entire project and cloning again I was able to properly move it.

**Comment by celluj34** [comment]
Looks much better now :)

**Comment by ndsvw** [comment]
I merged the pull request.
Thanks, @fraga and @celluj34.

**Comment by fraga** [comment]
@celluj34 @ndsvw anytime! Thanks to you for the tool!

**Pull request closed without merging**
